#!/bin/bash

# additional test script for basic merging (without conflicts)
# merge branch with new file
# treat a deleted branch in both files as no conflict

set -euo pipefail

readonly TEST_DIR=$(mktemp --tmpdir --directory lit-test.XXXXXX)

echo "== Using $TEST_DIR"
pushd "$TEST_DIR"

echo "== Initializing repository"
lit init

echo "== create commits r0, r1"

cat >file1 <<-EOF
	first line
EOF
lit commit "add file1"

echo >>file1 "line two"
lit commit "add line two"

echo "== checkout r0"
lit checkout r0


echo "== edit file1" 
echo >>file1 "line three"
lit commit "add line three"

echo "== checkout r1"
lit checkout r1

echo "== merge r2 into r1"
lit merge r2

test -f file1 && echo "OK: file1 here" || echo "FAIL: file1 not here"
test -f file1.r2 && echo "OK: file1.r2 here" || echo "FAIL: file1.r2 not here"

diff -s file1 - <<-EOF
	first line
	line two
EOF

diff -s file1.r2 - <<-EOF
	first line
	line three
EOF
