#!/bin/bash

# additional test script for basic merging (without conflicts)
# merge branch with new file
# treat a deleted branch in both files as no conflict

set -euo pipefail

readonly TEST_DIR=$(mktemp --tmpdir --directory lit-test.XXXXXX)

echo "== Using $TEST_DIR"
pushd "$TEST_DIR"

echo "== Initializing repository"
lit init

echo "== create commits r0, r1, r2"

cat >file1 <<-EOF
	first line
EOF
lit commit "add file1"

echo >>file1 "line two"
lit commit "add line two"


echo "== checkout r0"
lit checkout r0


echo "== create new file file2" 
cat >file2 <<-EOF
	first line of file2
EOF

lit commit "add file2"

echo "== checkout r2"
lit checkout r1

# file2 shouldn't be there
test ! -f file2

echo "== merge branch r2 into r1"
lit merge r2

# file2 should now be present.
diff -s file2 - <<-EOF
	first line of file2
EOF

echo "== check graph"
lit log > logfile
cat logfile
diff -s logfile - <<-EOF
	o  ┐                ⇽ r3: merge r2 into r1
	|  o                r2: add file2
	o  |                r1: add line two
	o  ┘                r0: add file1
EOF

